name = "slob-relay"
main = "src/index.js"
compatibility_date = "2024-09-23"
workers_dev = true

routes = [
  { pattern = "relay.slob.games", custom_domain = true }
]

[[kv_namespaces]]
binding = "AUTH_KV"
id = "2b8e99fa73694b72b1ba50e8c8445eaf"

[durable_objects]
bindings = [
  { name = "RELAY", class_name = "RelaySession" },
  { name = "GAME_ROOM", class_name = "GameRoomV6" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RelaySession"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["GameRoom"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["GameRoomV2"]

[[migrations]]
tag = "v4"
new_sqlite_classes = ["GameRoomV3"]

[[migrations]]
tag = "v5"
renamed_classes = [{from = "GameRoomV3", to = "GameRoomV4"}]

[[migrations]]
tag = "v6"
new_sqlite_classes = ["GameRoomV5"]

[[migrations]]
tag = "v7"
new_classes = ["GameRoomV6"]
